set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 0.980 -nets VDD -layer METAL7 -width 0.580 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 330.050 -nets VDD -layer METAL7 -width 0.580 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 314.210 -nets VDD -layer METAL8 -width 1.080 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.230 -nets VDD -layer METAL8 -width 1.080 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 12.285 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.945 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 33.605 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.855 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.515 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.175 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 75.425 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.085 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 96.745 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 107.405 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 117.655 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 128.315 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 138.975 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 149.225 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 159.885 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 170.545 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 177.430 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 181.205 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 191.455 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 203.970 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 191.455 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 257.430 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 202.115 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 212.775 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 223.025 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 233.685 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 244.345 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 254.595 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 265.255 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 275.915 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 286.575 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 296.825 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 307.485 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 318.145 -nets VDD  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 314.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 12.885 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.545 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.205 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.455 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 55.115 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 65.775 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.025 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.685 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 97.345 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 108.005 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 118.255 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 128.915 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 139.575 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 149.825 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 160.485 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 171.145 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 181.805 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 192.055 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 205.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 192.055 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 218.490 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 202.715 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 213.375 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 223.625 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 234.285 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 244.945 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 255.195 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 265.855 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 276.515 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 287.175 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 297.425 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 308.085 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 318.745 -nets VSS  -layer METAL7 -width 0.290 -pitch_within_group 10.540 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 311.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 16.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 56.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 83.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 96.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 110.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 123.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 136.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 150.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 163.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 177.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 190.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 203.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 217.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 189.750 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 217.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 248.290 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 230.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 244.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 257.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 271.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 23.090 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 271.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 93.310 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 284.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 297.700 -nets VDD  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 0.690 -start_high_ends coordinate  -start_high_ends_coordinate 330.340 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 17.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 70.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 97.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 111.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 124.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 137.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 151.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 164.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 178.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 191.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 218.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 231.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 245.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 258.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 272.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 23.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 272.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 97.000 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 285.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 298.760 -nets VSS  -layer METAL8 -width 0.540 -pitch_within_group 13.420 -start_low_ends coordinate  -start_low_ends_coordinate 3.500 -start_high_ends coordinate  -start_high_ends_coordinate 327.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
